project:
  type: book

book:
  title: "Domina JavaScript. +200 retos de programaci√≥n"
  author: "Cristian Fernando Villca Gutierrez"
  date: "1/12/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - agradecimientos.qmd
    - about.qmd
    - references.qmd
    - retos.qmd
    - soluciones.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    include-before-body:
      - text: |
          \begin{titlepage}
          \centering
          \vspace*{\fill}
          \includegraphics[width=\textwidth, height=\textheight, keepaspectratio]{photos/portada.png}
          \vspace*{\fill}
          \end{titlepage}



